//------------------------------------------------------------------------------
// <auto-generated>
//   Strongly-typed UI resource accessors for UiResources.resx
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Globalization;
using System.Resources;

namespace OpenMES.Localization.Resources;

public static class UiResources
{
    private static ResourceManager? _resourceManager;
    public static ResourceManager ResourceManager
    {
        get
        {
            _resourceManager ??= new ResourceManager(
                "OpenMES.Localization.Resources.UiResources",
                typeof(UiResources).Assembly);
            return _resourceManager;
        }
    }

    public static CultureInfo? Culture { get; set; }
    private static string GetString(string name) => ResourceManager.GetString(name, Culture) ?? name;

    public static string Action_ActivePhase => GetString(nameof(Action_ActivePhase));
    public static string Action_Cancel => GetString(nameof(Action_Cancel));
    public static string Action_CheckIn => GetString(nameof(Action_CheckIn));
    public static string Action_CheckOut => GetString(nameof(Action_CheckOut));
    public static string Action_ChooseSessionType => GetString(nameof(Action_ChooseSessionType));
    public static string Action_CloseSession => GetString(nameof(Action_CloseSession));
    public static string Action_Confirmed => GetString(nameof(Action_Confirmed));
    public static string Action_Confirm => GetString(nameof(Action_Confirm));
    public static string Action_DeclareQty => GetString(nameof(Action_DeclareQty));
    public static string Action_GoodPieces => GetString(nameof(Action_GoodPieces));
    public static string Action_MachineStop => GetString(nameof(Action_MachineStop));
    public static string Action_Order => GetString(nameof(Action_Order));
    public static string Action_ScanOrTypeBarcode => GetString(nameof(Action_ScanOrTypeBarcode));
    public static string Action_ScrapOptional => GetString(nameof(Action_ScrapOptional));
    public static string Action_SelectPhase => GetString(nameof(Action_SelectPhase));
    public static string Action_SessionOpen => GetString(nameof(Action_SessionOpen));
    public static string Action_SessionSetup => GetString(nameof(Action_SessionSetup));
    public static string Action_SessionWork => GetString(nameof(Action_SessionWork));
    public static string Action_StartWork => GetString(nameof(Action_StartWork));
    public static string Action_TargetQty => GetString(nameof(Action_TargetQty));
    public static string Action_TotalQty => GetString(nameof(Action_TotalQty));
    public static string Action_TotalExceedsTarget => GetString(nameof(Action_TotalExceedsTarget));
    public static string Action_LastDeclarations => GetString(nameof(Action_LastDeclarations));
    public static string Action_NoDeclarations => GetString(nameof(Action_NoDeclarations));
    public static string Action_ConfirmDeclarationTitle => GetString(nameof(Action_ConfirmDeclarationTitle));
    public static string Action_ConfirmDeclarationMessage => GetString(nameof(Action_ConfirmDeclarationMessage));
    public static string Action_ErrorMachineNotLoaded => GetString(nameof(Action_ErrorMachineNotLoaded));
    public static string Action_ErrorOperatorMissing => GetString(nameof(Action_ErrorOperatorMissing));
    public static string Action_ErrorDeclarationFailed => GetString(nameof(Action_ErrorDeclarationFailed));
    public static string Action_ErrorNoActivePhaseForMachine => GetString(nameof(Action_ErrorNoActivePhaseForMachine));
    public static string Action_ErrorOpenSessionFailed => GetString(nameof(Action_ErrorOpenSessionFailed));
    public static string Action_Operator => GetString(nameof(Action_Operator));
    public static string Action_ShiftStatus => GetString(nameof(Action_ShiftStatus));
    public static string Action_ShiftDuration => GetString(nameof(Action_ShiftDuration));
    public static string Action_NoOperator => GetString(nameof(Action_NoOperator));
    public static string Action_ShiftCheckedIn => GetString(nameof(Action_ShiftCheckedIn));
    public static string Action_ShiftOnBreak => GetString(nameof(Action_ShiftOnBreak));
    public static string Action_ShiftCheckedOut => GetString(nameof(Action_ShiftCheckedOut));
    public static string Action_TakeBreak => GetString(nameof(Action_TakeBreak));
    public static string Action_ReturnFromBreak => GetString(nameof(Action_ReturnFromBreak));
    public static string Action_CheckOutWarningTitle => GetString(nameof(Action_CheckOutWarningTitle));
    public static string Action_CheckOutWarningMessage => GetString(nameof(Action_CheckOutWarningMessage));
    public static string Action_ErrorNoOperators => GetString(nameof(Action_ErrorNoOperators));
    public static string Action_ErrorShiftUpdateFailed => GetString(nameof(Action_ErrorShiftUpdateFailed));
    public static string Action_StateDuration => GetString(nameof(Action_StateDuration));
    public static string Action_StatePaused => GetString(nameof(Action_StatePaused));
    public static string Action_Start => GetString(nameof(Action_Start));
    public static string Action_Pause => GetString(nameof(Action_Pause));
    public static string Action_Stop => GetString(nameof(Action_Stop));
    public static string Action_Resume => GetString(nameof(Action_Resume));
    public static string Action_SelectStopReason => GetString(nameof(Action_SelectStopReason));
    public static string Action_SearchStopReason => GetString(nameof(Action_SearchStopReason));
    public static string Action_ErrorNoStopReasons => GetString(nameof(Action_ErrorNoStopReasons));
    public static string Action_ErrorStateChangeFailed => GetString(nameof(Action_ErrorStateChangeFailed));
    public static string Action_StopDurationSeconds => GetString(nameof(Action_StopDurationSeconds));
    public static string Action_PlacementsTitle => GetString(nameof(Action_PlacementsTitle));
    public static string Action_NoPlacementsForMachine => GetString(nameof(Action_NoPlacementsForMachine));
    public static string Action_PlacementStatusPlaced => GetString(nameof(Action_PlacementStatusPlaced));
    public static string Action_PlacementStatusInSetup => GetString(nameof(Action_PlacementStatusInSetup));
    public static string Action_PlacementStatusSetupPaused => GetString(nameof(Action_PlacementStatusSetupPaused));
    public static string Action_PlacementStatusInWork => GetString(nameof(Action_PlacementStatusInWork));
    public static string Action_PlacementStatusWorkPaused => GetString(nameof(Action_PlacementStatusWorkPaused));
    public static string Action_PlacementStatusClosed => GetString(nameof(Action_PlacementStatusClosed));
    public static string Action_PlacementSetup => GetString(nameof(Action_PlacementSetup));
    public static string Action_PlacementWork => GetString(nameof(Action_PlacementWork));
    public static string Action_PlacementPauseSetup => GetString(nameof(Action_PlacementPauseSetup));
    public static string Action_PlacementSwitchToWork => GetString(nameof(Action_PlacementSwitchToWork));
    public static string Action_PlacementResumeSetup => GetString(nameof(Action_PlacementResumeSetup));
    public static string Action_PlacementStartWork => GetString(nameof(Action_PlacementStartWork));
    public static string Action_PlacementPauseWork => GetString(nameof(Action_PlacementPauseWork));
    public static string Action_PlacementResumeWork => GetString(nameof(Action_PlacementResumeWork));
    public static string Action_PlacementClose => GetString(nameof(Action_PlacementClose));
    public static string Action_PlacementCloseConfirm => GetString(nameof(Action_PlacementCloseConfirm));
    public static string Action_ConfirmedShort => GetString(nameof(Action_ConfirmedShort));
    public static string Action_ScrapShort => GetString(nameof(Action_ScrapShort));
    public static string Action_GuideTitle => GetString(nameof(Action_GuideTitle));
    public static string Action_GuideStepOperator => GetString(nameof(Action_GuideStepOperator));
    public static string Action_GuideStepOperatorSelected => GetString(nameof(Action_GuideStepOperatorSelected));
    public static string Action_GuideStepPhase => GetString(nameof(Action_GuideStepPhase));
    public static string Action_GuideStepPhaseSelected => GetString(nameof(Action_GuideStepPhaseSelected));
    public static string Action_GuideStepSession => GetString(nameof(Action_GuideStepSession));
    public static string Action_GuideStepSessionOpen => GetString(nameof(Action_GuideStepSessionOpen));
    public static string Action_GuideSelectPhaseCta => GetString(nameof(Action_GuideSelectPhaseCta));

    public static string Tab_Department => GetString(nameof(Tab_Department));
    public static string Tab_OperatorsMachines => GetString(nameof(Tab_OperatorsMachines));
    public static string Kpi_ActiveOrders => GetString(nameof(Kpi_ActiveOrders));
    public static string Kpi_OpenSessions => GetString(nameof(Kpi_OpenSessions));
    public static string Section_MachineStatus => GetString(nameof(Section_MachineStatus));
    public static string Kpi_ActiveStops => GetString(nameof(Kpi_ActiveStops));
    public static string Kpi_OpenNc => GetString(nameof(Kpi_OpenNc));
    public static string NoActiveStops => GetString(nameof(NoActiveStops));
    public static string NoOpenNc => GetString(nameof(NoOpenNc));
    public static string Period_Today => GetString(nameof(Period_Today));
    public static string Period_Week => GetString(nameof(Period_Week));
    public static string Period_Month => GetString(nameof(Period_Month));
    public static string Kpi_PresentOperators => GetString(nameof(Kpi_PresentOperators));
    public static string Kpi_HoursWorked => GetString(nameof(Kpi_HoursWorked));
    public static string Kpi_DeclaredPieces => GetString(nameof(Kpi_DeclaredPieces));
    public static string Kpi_OeeDept => GetString(nameof(Kpi_OeeDept));
    public static string Section_PresenceOperators => GetString(nameof(Section_PresenceOperators));
    public static string NoOpenSessions => GetString(nameof(NoOpenSessions));
    public static string NoDeclarationsToday => GetString(nameof(NoDeclarationsToday));
    public static string Section_OpenSessions => GetString(nameof(Section_OpenSessions));
    public static string Section_ActiveOrders => GetString(nameof(Section_ActiveOrders));
    public static string Section_LastDeclarations => GetString(nameof(Section_LastDeclarations));

    public static string Machine_Running => GetString(nameof(Machine_Running));
    public static string Machine_Setup => GetString(nameof(Machine_Setup));
    public static string Machine_Idle => GetString(nameof(Machine_Idle));
    public static string Machine_Stopped => GetString(nameof(Machine_Stopped));
    public static string Machine_Fault => GetString(nameof(Machine_Fault));
    public static string Machine_Maintenance => GetString(nameof(Machine_Maintenance));
    public static string Session_Work => GetString(nameof(Session_Work));
    public static string Session_Setup => GetString(nameof(Session_Setup));
    public static string Session_Wait => GetString(nameof(Session_Wait));
    public static string Session_Rework => GetString(nameof(Session_Rework));
    public static string Action_Started => GetString(nameof(Action_Started));
    public static string Action_Scrap => GetString(nameof(Action_Scrap));
    public static string Machine_Blocked => GetString(nameof(Machine_Blocked));
    public static string Machine_Starved => GetString(nameof(Machine_Starved));
    public static string Machine_Manual => GetString(nameof(Machine_Manual));
    public static string MachineCard_NoOperator => GetString(nameof(MachineCard_NoOperator));

    public static string Login_Title => GetString(nameof(Login_Title));
    public static string Login_DeviceName => GetString(nameof(Login_DeviceName));
    public static string Login_DeviceNamePlaceholder => GetString(nameof(Login_DeviceNamePlaceholder));
    public static string Login_Password => GetString(nameof(Login_Password));
    public static string Login_PasswordPlaceholder => GetString(nameof(Login_PasswordPlaceholder));
    public static string Login_Connect => GetString(nameof(Login_Connect));

    public static string User_EmailPlaceholder => GetString(nameof(User_EmailPlaceholder));
    public static string User_PasswordLabel => GetString(nameof(User_PasswordLabel));
    public static string User_NewPasswordLabel => GetString(nameof(User_NewPasswordLabel));
    public static string User_RolesLabel => GetString(nameof(User_RolesLabel));
    public static string User_SaveButton => GetString(nameof(User_SaveButton));
    public static string User_CancelButton => GetString(nameof(User_CancelButton));
    public static string User_ErrorEmailRequired => GetString(nameof(User_ErrorEmailRequired));
    public static string User_ErrorPasswordRequired => GetString(nameof(User_ErrorPasswordRequired));
    public static string User_StatusLabel => GetString(nameof(User_StatusLabel));
    public static string User_StatusActive => GetString(nameof(User_StatusActive));
    public static string User_StatusBlocked => GetString(nameof(User_StatusBlocked));
    public static string User_EditButton => GetString(nameof(User_EditButton));
    public static string User_UnlockButton => GetString(nameof(User_UnlockButton));
    public static string User_DeleteButton => GetString(nameof(User_DeleteButton));

    public static string Home_Title => GetString(nameof(Home_Title));
    public static string Home_Tab1_ActiveStops => GetString(nameof(Home_Tab1_ActiveStops));
    public static string Home_Tab1_OpenNc => GetString(nameof(Home_Tab1_OpenNc));
    public static string Home_Tab1_OpenSessions => GetString(nameof(Home_Tab1_OpenSessions));
    public static string Home_Tab1_NoOpenSessions => GetString(nameof(Home_Tab1_NoOpenSessions));
    public static string Home_Tab1_OrderStatus_Completed => GetString(nameof(Home_Tab1_OrderStatus_Completed));
    public static string Home_Tab1_OrderStatus_InProgress => GetString(nameof(Home_Tab1_OrderStatus_InProgress));
    public static string Home_Tab1_ActiveOrders => GetString(nameof(Home_Tab1_ActiveOrders));
    public static string Home_Kpi_ErpPending => GetString(nameof(Home_Kpi_ErpPending));
    public static string Home_Kpi_Picking => GetString(nameof(Home_Kpi_Picking));
    public static string Home_Kpi_PickingSubtext => GetString(nameof(Home_Kpi_PickingSubtext));
    public static string Home_Kpi_StockAlert => GetString(nameof(Home_Kpi_StockAlert));
    public static string Home_Kpi_StockAlertSubtext => GetString(nameof(Home_Kpi_StockAlertSubtext));
    public static string Home_Tab2_OperatorPresence => GetString(nameof(Home_Tab2_OperatorPresence));
    public static string Home_Tab2_MachineEfficiency => GetString(nameof(Home_Tab2_MachineEfficiency));
    public static string Home_Tab2_MachineEfficiency_Run => GetString(nameof(Home_Tab2_MachineEfficiency_Run));
    public static string Home_Tab2_MachineEfficiency_Stop => GetString(nameof(Home_Tab2_MachineEfficiency_Stop));
    public static string Home_Tab2_TopProducers => GetString(nameof(Home_Tab2_TopProducers));
    public static string Home_Tab2_ScrapRate => GetString(nameof(Home_Tab2_ScrapRate));
    public static string Home_Tab2_RecentDeclarations => GetString(nameof(Home_Tab2_RecentDeclarations));
    public static string Home_Tab2_NoDeclarations => GetString(nameof(Home_Tab2_NoDeclarations));
    public static string Home_Status_Present => GetString(nameof(Home_Status_Present));
    public static string Home_Status_Break => GetString(nameof(Home_Status_Break));
    public static string Home_Status_Absent => GetString(nameof(Home_Status_Absent));
    public static string OperatorBadge_StatusOffline => GetString(nameof(OperatorBadge_StatusOffline));
    public static string Session_ExpiredInactivity => GetString(nameof(Session_ExpiredInactivity));

    public static string Auth_CheckingAuthentication => GetString(nameof(Auth_CheckingAuthentication));
    public static string Auth_AccessDenied => GetString(nameof(Auth_AccessDenied));
    public static string Auth_NoPermissionPage => GetString(nameof(Auth_NoPermissionPage));
    public static string Auth_SessionExpiredOrUnauthenticated => GetString(nameof(Auth_SessionExpiredOrUnauthenticated));
    public static string Auth_RedirectingToLogin => GetString(nameof(Auth_RedirectingToLogin));
    public static string Auth_ClickIfNotRedirected => GetString(nameof(Auth_ClickIfNotRedirected));

    public static string Dialog_SelectOperator => GetString(nameof(Dialog_SelectOperator));
    public static string Dialog_SearchOperator => GetString(nameof(Dialog_SearchOperator));

    public static string Error_HttpUnauthorized => GetString(nameof(Error_HttpUnauthorized));
    public static string Error_HttpForbidden => GetString(nameof(Error_HttpForbidden));
    public static string Error_HttpNotFound => GetString(nameof(Error_HttpNotFound));
    public static string Error_HttpBadRequestPrefix => GetString(nameof(Error_HttpBadRequestPrefix));
    public static string Error_HttpInternalServer => GetString(nameof(Error_HttpInternalServer));
    public static string Error_HttpServiceUnavailable => GetString(nameof(Error_HttpServiceUnavailable));
    public static string Error_HttpCommunicationPrefix => GetString(nameof(Error_HttpCommunicationPrefix));
    public static string Error_GenericOccurredPrefix => GetString(nameof(Error_GenericOccurredPrefix));
    public static string Home_StopReason_Breakdown => GetString(nameof(Home_StopReason_Breakdown));
    public static string Home_StopReason_Other => GetString(nameof(Home_StopReason_Other));
    public static string Home_NC_Severity_Critical => GetString(nameof(Home_NC_Severity_Critical));
    public static string Home_NC_Severity_High => GetString(nameof(Home_NC_Severity_High));
    public static string Home_KpiSubtext_CurrentShift => GetString(nameof(Home_KpiSubtext_CurrentShift));
    public static string Home_KpiSubtext_Days => GetString(nameof(Home_KpiSubtext_Days));
    public static string Home_KpiSubtext_Scrap => GetString(nameof(Home_KpiSubtext_Scrap));
    public static string Home_KpiSubtext_InBreak => GetString(nameof(Home_KpiSubtext_InBreak));
    public static string Home_KpiSubtext_Absent => GetString(nameof(Home_KpiSubtext_Absent));

    public static string WebAdmin_Login_Title => GetString(nameof(WebAdmin_Login_Title));
    public static string WebAdmin_Login_EmailPlaceholder => GetString(nameof(WebAdmin_Login_EmailPlaceholder));
    public static string WebAdmin_Login_LoginButton => GetString(nameof(WebAdmin_Login_LoginButton));
    public static string WebAdmin_Login_ErrorRequiredFields => GetString(nameof(WebAdmin_Login_ErrorRequiredFields));

    public static string NavMenu_Administration => GetString(nameof(NavMenu_Administration));
    public static string NavMenu_Users => GetString(nameof(NavMenu_Users));
    public static string NavMenu_Home => GetString(nameof(NavMenu_Home));
    public static string NavMenu_MasterData => GetString(nameof(NavMenu_MasterData));
    public static string NavMenu_Plants => GetString(nameof(NavMenu_Plants));
    public static string NavMenu_WorkCenters => GetString(nameof(NavMenu_WorkCenters));
    public static string NavMenu_Machines => GetString(nameof(NavMenu_Machines));
    public static string NavMenu_Operators => GetString(nameof(NavMenu_Operators));
    public static string NavMenu_Materials => GetString(nameof(NavMenu_Materials));
    public static string NavMenu_ClientDevices => GetString(nameof(NavMenu_ClientDevices));
    public static string NavMenu_Production => GetString(nameof(NavMenu_Production));
    public static string NavMenu_ProductionOrders => GetString(nameof(NavMenu_ProductionOrders));
    public static string NavMenu_PickingLists => GetString(nameof(NavMenu_PickingLists));
    public static string NavMenu_ProductionDeclarations => GetString(nameof(NavMenu_ProductionDeclarations));
    public static string NavMenu_Declarations => GetString(nameof(NavMenu_Declarations));
    public static string NavMenu_OperatorShifts => GetString(nameof(NavMenu_OperatorShifts));
    public static string NavMenu_WorkSessions => GetString(nameof(NavMenu_WorkSessions));
    public static string NavMenu_ErpExport => GetString(nameof(NavMenu_ErpExport));
    public static string NavMenu_MachineStates => GetString(nameof(NavMenu_MachineStates));
    public static string NavMenu_MachineStops => GetString(nameof(NavMenu_MachineStops));
    public static string NavMenu_StopReasons => GetString(nameof(NavMenu_StopReasons));
    public static string NavMenu_Quality => GetString(nameof(NavMenu_Quality));
    public static string NavMenu_InspectionPlans => GetString(nameof(NavMenu_InspectionPlans));
    public static string NavMenu_InspectionReadings => GetString(nameof(NavMenu_InspectionReadings));
    public static string NavMenu_NonConformities => GetString(nameof(NavMenu_NonConformities));
    public static string NavMenu_Warehouse => GetString(nameof(NavMenu_Warehouse));
    public static string NavMenu_StorageLocations => GetString(nameof(NavMenu_StorageLocations));
    public static string NavMenu_MaterialStock => GetString(nameof(NavMenu_MaterialStock));
    public static string NavMenu_StockMovements => GetString(nameof(NavMenu_StockMovements));

    public static string Label_Open => GetString(nameof(Label_Open));
    public static string Label_Quantity => GetString(nameof(Label_Quantity));
    public static string Label_PickedQuantity => GetString(nameof(Label_PickedQuantity));
    public static string Label_PickedAt => GetString(nameof(Label_PickedAt));
    public static string Label_Mandatory => GetString(nameof(Label_Mandatory));
    public static string Label_Seq => GetString(nameof(Label_Seq));
    public static string Label_NominalValue => GetString(nameof(Label_NominalValue));
    public static string Label_MeasureType => GetString(nameof(Label_MeasureType));
    public static string Label_Auto => GetString(nameof(Label_Auto));
    public static string Label_Consumable => GetString(nameof(Label_Consumable));
    public static string Label_Phantom => GetString(nameof(Label_Phantom));
    public static string Label_Actions => GetString(nameof(Label_Actions));
    public static string Label_Logout => GetString(nameof(Label_Logout));
    public static string Label_LogoutConfirm => GetString(nameof(Label_LogoutConfirm));

    public static string Button_Add => GetString(nameof(Button_Add));
    public static string Button_Cancel => GetString(nameof(Button_Cancel));
    public static string Button_Close => GetString(nameof(Button_Close));
    public static string Button_Delete => GetString(nameof(Button_Delete));
    public static string Button_Edit => GetString(nameof(Button_Edit));
    public static string Button_Save => GetString(nameof(Button_Save));
}
