# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
# Using Alpine with ICU data packages for globalization/culture support
FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS base
USER root
RUN apk add --no-cache icu-libs icu-data-full
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["OpenMES.WebAdmin/OpenMES.WebAdmin.csproj", "OpenMES.WebAdmin/"]
COPY ["OpenMES.Data.Dtos/OpenMES.Data.Dtos.csproj", "OpenMES.Data.Dtos/"]
COPY ["OpenMES.Data.Common/OpenMES.Data.Common.csproj", "OpenMES.Data.Common/"]
COPY ["OpenMES.ServiceDefaults/OpenMES.ServiceDefaults.csproj", "OpenMES.ServiceDefaults/"]
COPY ["OpenMES.WebApiClient/OpenMES.WebApiClient.csproj", "OpenMES.WebApiClient/"]
RUN dotnet restore "./OpenMES.WebAdmin/OpenMES.WebAdmin.csproj"
COPY . .
WORKDIR "/src/OpenMES.WebAdmin"
RUN dotnet build "./OpenMES.WebAdmin.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./OpenMES.WebAdmin.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OpenMES.WebAdmin.dll"]