using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using OpenMES.Data.Common;
using OpenMES.Data.Dtos;
using OpenMES.Data.Entities.Interfaces;
using OpenMES.Data.Interfaces;

namespace OpenMES.Data.Entities;

/// <summary>
/// Records a single picking event against a <see cref="PhasePickingList"/> line.
/// Each picking item represents the physical withdrawal of material from stock.
///
/// On creation, a <see cref="StockMovement"/> of type <c>ProductionIssue</c> is
/// generated automatically. The stock movement decreases <see cref="MaterialStock"/>
/// at the source location and the <see cref="PhasePickingList.PickedQuantity"/>
/// is incremented accordingly.
///
/// <see cref="IsAutomatic"/> distinguishes between:
/// - Automatic picks: triggered by a <see cref="ProductionDeclaration"/> when
///   <see cref="PhasePickingList.IsAutomatic"/> is true — quantity is proportional
///   to the declared production quantity.
/// - Manual picks: registered explicitly by an operator via the terminal.
///
/// Records are never modified after creation. Corrections are made by issuing
/// a new <see cref="StockMovement"/> of type <c>Adjustment</c>.
/// </summary>
[Table(nameof(PhasePickingItem))]
[PrimaryKey(nameof(Id))]
public class PhasePickingItem : IKey<int>, IBaseDates, IDtoAdapter<PhasePickingItem, PhasePickingItemDto>
{
	public int Id { get; set; }

	/// <summary>FK to the picking list line this item fulfills.</summary>
	public int PhasePickingListId { get; set; }

	/// <summary>FK to the stock movement generated by this picking item.</summary>
	public int StockMovementId { get; set; }

	/// <summary>Quantity picked in this event.</summary>
	[Precision(9, 3)]
	public decimal PickedQuantity { get; set; }

	/// <summary>Date and time when the picking was performed.</summary>
	public DateTimeOffset PickedAt { get; set; }

	/// <summary>FK to the operator who performed or confirmed the picking.</summary>
	public int OperatorId { get; set; }

	/// <summary>True when this item was generated automatically by a ProductionDeclaration.</summary>
	public bool IsAutomatic { get; set; }

	[StringLength(500)]
	public string? Notes { get; set; }

	public DateTimeOffset CreatedAt { get; set; }
	public DateTimeOffset UpdatedAt { get; set; }

	[ForeignKey(nameof(PhasePickingListId))]
	[InverseProperty(nameof(PhasePickingList.PickingItems))]
	public virtual PhasePickingList PhasePickingList { get; set; } = null!;

	[ForeignKey(nameof(StockMovementId))]
	public virtual StockMovement StockMovement { get; set; } = null!;

	[ForeignKey(nameof(OperatorId))]
	public virtual Operator Operator { get; set; } = null!;

	public static PhasePickingItemDto AsDto(PhasePickingItem entity) => new()
	{
		Id = entity.Id,
		PhasePickingListId = entity.PhasePickingListId,
		StockMovementId = entity.StockMovementId,
		PickedQuantity = entity.PickedQuantity,
		PickedAt = entity.PickedAt,
		OperatorId = entity.OperatorId,
		IsAutomatic = entity.IsAutomatic,
		Notes = entity.Notes,
		CreatedAt = entity.CreatedAt,
		UpdatedAt = entity.UpdatedAt,
		OperatorName = entity.Operator?.Name,
		PartNumber = entity.PhasePickingList?.Material?.PartNumber,
		StorageLocationCode = entity.PhasePickingList?.StorageLocation?.Code,
	};

	public static PhasePickingItem AsEntity(PhasePickingItemDto dto) => new()
	{
		Id = dto.Id,
		PhasePickingListId = dto.PhasePickingListId,
		StockMovementId = dto.StockMovementId,
		PickedQuantity = dto.PickedQuantity,
		PickedAt = dto.PickedAt,
		OperatorId = dto.OperatorId,
		IsAutomatic = dto.IsAutomatic,
		Notes = dto.Notes,
	};
}
