//------------------------------------------------------------------------------
// <auto-generated>
//   This file is maintained manually to match DtoResources.resx.
//   In Visual Studio: set DtoResources.resx Build Action = "EmbeddedResource"
//   and Custom Tool = "PublicResXFileCodeGenerator" to auto-generate this file.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Globalization;
using System.Resources;

namespace OpenMES.Data.Dtos.Resources;

/// <summary>
/// Strongly-typed resource class for DTO property display names.
/// Used with <see cref="System.ComponentModel.DisplayNameAttribute"/> to support localization.
/// </summary>
public static class DtoResources
{
    private static ResourceManager? _resourceManager;

    /// <summary>Returns the cached ResourceManager for this class.</summary>
    public static ResourceManager ResourceManager
    {
        get
        {
            _resourceManager ??= new ResourceManager(
                "OpenMES.Data.Dtos.Resources.DtoResources",
                typeof(DtoResources).Assembly);
            return _resourceManager;
        }
    }

    /// <summary>Returns the current thread UI culture, used for resource lookup.</summary>
    public static CultureInfo? Culture { get; set; }

    private static string GetString(string name) =>
        ResourceManager.GetString(name, Culture) ?? name;

    // ── MachineStopReasonDto ──────────────────────────────────────────────────
    /// <summary>Display name for <see cref="MachineStopReasonDto.Code"/>.</summary>
    public static string MachineStopReason_Code        => GetString(nameof(MachineStopReason_Code));
    /// <summary>Display name for <see cref="MachineStopReasonDto.Description"/>.</summary>
    public static string MachineStopReason_Description => GetString(nameof(MachineStopReason_Description));
    /// <summary>Display name for <see cref="MachineStopReasonDto.Category"/>.</summary>
    public static string MachineStopReason_Category    => GetString(nameof(MachineStopReason_Category));
    /// <summary>Display name for <see cref="MachineStopReasonDto.Disabled"/>.</summary>
    public static string MachineStopReason_Disabled    => GetString(nameof(MachineStopReason_Disabled));

    // ── MachineStopDto ────────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="MachineStopDto.MachineId"/>.</summary>
    public static string MachineStop_MachineId              => GetString(nameof(MachineStop_MachineId));
    /// <summary>Display name for <see cref="MachineStopDto.ProductionOrderPhaseId"/>.</summary>
    public static string MachineStop_ProductionOrderPhaseId => GetString(nameof(MachineStop_ProductionOrderPhaseId));
    /// <summary>Display name for <see cref="MachineStopDto.MachineStopReasonId"/>.</summary>
    public static string MachineStop_MachineStopReasonId    => GetString(nameof(MachineStop_MachineStopReasonId));
    /// <summary>Display name for <see cref="MachineStopDto.StartDate"/>.</summary>
    public static string MachineStop_StartDate              => GetString(nameof(MachineStop_StartDate));
    /// <summary>Display name for <see cref="MachineStopDto.EndDate"/>.</summary>
    public static string MachineStop_EndDate                => GetString(nameof(MachineStop_EndDate));
    /// <summary>Display name for <see cref="MachineStopDto.Notes"/>.</summary>
    public static string MachineStop_Notes                  => GetString(nameof(MachineStop_Notes));
    /// <summary>Display name for <see cref="MachineStopDto.MachineCode"/>.</summary>
    public static string MachineStop_MachineCode            => GetString(nameof(MachineStop_MachineCode));
    /// <summary>Display name for <see cref="MachineStopDto.MachineStopReasonCode"/>.</summary>
    public static string MachineStop_ReasonCode             => GetString(nameof(MachineStop_ReasonCode));
    /// <summary>Display name for <see cref="MachineStopDto.MachineStopReasonDescription"/>.</summary>
    public static string MachineStop_ReasonDescription      => GetString(nameof(MachineStop_ReasonDescription));
    /// <summary>Display name for <see cref="MachineStopDto.MachineStopReasonCategory"/>.</summary>
    public static string MachineStop_ReasonCategory         => GetString(nameof(MachineStop_ReasonCategory));

    // ── ProductionDeclarationDto ──────────────────────────────────────────────
    /// <summary>Display name for <see cref="ProductionDeclarationDto.ProductionOrderPhaseId"/>.</summary>
    public static string ProductionDeclaration_ProductionOrderPhaseId => GetString(nameof(ProductionDeclaration_ProductionOrderPhaseId));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.OperatorId"/>.</summary>
    public static string ProductionDeclaration_OperatorId             => GetString(nameof(ProductionDeclaration_OperatorId));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.MachineId"/>.</summary>
    public static string ProductionDeclaration_MachineId              => GetString(nameof(ProductionDeclaration_MachineId));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.DeclarationDate"/>.</summary>
    public static string ProductionDeclaration_DeclarationDate        => GetString(nameof(ProductionDeclaration_DeclarationDate));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.ConfirmedQuantity"/>.</summary>
    public static string ProductionDeclaration_ConfirmedQuantity      => GetString(nameof(ProductionDeclaration_ConfirmedQuantity));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.ScrapQuantity"/>.</summary>
    public static string ProductionDeclaration_ScrapQuantity          => GetString(nameof(ProductionDeclaration_ScrapQuantity));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.Notes"/>.</summary>
    public static string ProductionDeclaration_Notes                  => GetString(nameof(ProductionDeclaration_Notes));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.PhaseExternalId"/>.</summary>
    public static string ProductionDeclaration_PhaseExternalId        => GetString(nameof(ProductionDeclaration_PhaseExternalId));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.ExternalCounterId"/>.</summary>
    public static string ProductionDeclaration_ExternalCounterId      => GetString(nameof(ProductionDeclaration_ExternalCounterId));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.ErpExportedAt"/>.</summary>
    public static string ProductionDeclaration_ErpExportedAt          => GetString(nameof(ProductionDeclaration_ErpExportedAt));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.IsReversal"/>.</summary>
    public static string ProductionDeclaration_IsReversal             => GetString(nameof(ProductionDeclaration_IsReversal));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.ReversalOfId"/>.</summary>
    public static string ProductionDeclaration_ReversalOfId           => GetString(nameof(ProductionDeclaration_ReversalOfId));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.ReversedById"/>.</summary>
    public static string ProductionDeclaration_ReversedById           => GetString(nameof(ProductionDeclaration_ReversedById));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.PhaseNumber"/>.</summary>
    public static string ProductionDeclaration_PhaseNumber            => GetString(nameof(ProductionDeclaration_PhaseNumber));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.OperatorName"/>.</summary>
    public static string ProductionDeclaration_OperatorName           => GetString(nameof(ProductionDeclaration_OperatorName));
    /// <summary>Display name for <see cref="ProductionDeclarationDto.MachineCode"/>.</summary>
    public static string ProductionDeclaration_MachineCode            => GetString(nameof(ProductionDeclaration_MachineCode));

    // ── InspectionPlanDto ─────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="InspectionPlanDto.Code"/>.</summary>
    public static string InspectionPlan_Code        => GetString(nameof(InspectionPlan_Code));
    /// <summary>Display name for <see cref="InspectionPlanDto.Description"/>.</summary>
    public static string InspectionPlan_Description => GetString(nameof(InspectionPlan_Description));
    /// <summary>Display name for <see cref="InspectionPlanDto.PartNumber"/>.</summary>
    public static string InspectionPlan_PartNumber  => GetString(nameof(InspectionPlan_PartNumber));
    /// <summary>Display name for <see cref="InspectionPlanDto.Version"/>.</summary>
    public static string InspectionPlan_Version     => GetString(nameof(InspectionPlan_Version));
    /// <summary>Display name for <see cref="InspectionPlanDto.Disabled"/>.</summary>
    public static string InspectionPlan_Disabled    => GetString(nameof(InspectionPlan_Disabled));

    // ── InspectionPointDto ────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="InspectionPointDto.InspectionPlanId"/>.</summary>
    public static string InspectionPoint_InspectionPlanId => GetString(nameof(InspectionPoint_InspectionPlanId));
    /// <summary>Display name for <see cref="InspectionPointDto.Sequence"/>.</summary>
    public static string InspectionPoint_Sequence         => GetString(nameof(InspectionPoint_Sequence));
    /// <summary>Display name for <see cref="InspectionPointDto.Description"/>.</summary>
    public static string InspectionPoint_Description      => GetString(nameof(InspectionPoint_Description));
    /// <summary>Display name for <see cref="InspectionPointDto.MeasureType"/>.</summary>
    public static string InspectionPoint_MeasureType      => GetString(nameof(InspectionPoint_MeasureType));
    /// <summary>Display name for <see cref="InspectionPointDto.NominalValue"/>.</summary>
    public static string InspectionPoint_NominalValue     => GetString(nameof(InspectionPoint_NominalValue));
    /// <summary>Display name for <see cref="InspectionPointDto.UpperTolerance"/>.</summary>
    public static string InspectionPoint_UpperTolerance   => GetString(nameof(InspectionPoint_UpperTolerance));
    /// <summary>Display name for <see cref="InspectionPointDto.LowerTolerance"/>.</summary>
    public static string InspectionPoint_LowerTolerance   => GetString(nameof(InspectionPoint_LowerTolerance));
    /// <summary>Display name for <see cref="InspectionPointDto.UnitOfMeasure"/>.</summary>
    public static string InspectionPoint_UnitOfMeasure    => GetString(nameof(InspectionPoint_UnitOfMeasure));
    /// <summary>Display name for <see cref="InspectionPointDto.IsMandatory"/>.</summary>
    public static string InspectionPoint_IsMandatory      => GetString(nameof(InspectionPoint_IsMandatory));

    // ── InspectionReadingDto ──────────────────────────────────────────────────
    /// <summary>Display name for <see cref="InspectionReadingDto.InspectionPointId"/>.</summary>
    public static string InspectionReading_InspectionPointId      => GetString(nameof(InspectionReading_InspectionPointId));
    /// <summary>Display name for <see cref="InspectionReadingDto.ProductionOrderPhaseId"/>.</summary>
    public static string InspectionReading_ProductionOrderPhaseId => GetString(nameof(InspectionReading_ProductionOrderPhaseId));
    /// <summary>Display name for <see cref="InspectionReadingDto.OperatorId"/>.</summary>
    public static string InspectionReading_OperatorId             => GetString(nameof(InspectionReading_OperatorId));
    /// <summary>Display name for <see cref="InspectionReadingDto.ReadingDate"/>.</summary>
    public static string InspectionReading_ReadingDate            => GetString(nameof(InspectionReading_ReadingDate));
    /// <summary>Display name for <see cref="InspectionReadingDto.NumericValue"/>.</summary>
    public static string InspectionReading_NumericValue           => GetString(nameof(InspectionReading_NumericValue));
    /// <summary>Display name for <see cref="InspectionReadingDto.BooleanValue"/>.</summary>
    public static string InspectionReading_BooleanValue           => GetString(nameof(InspectionReading_BooleanValue));
    /// <summary>Display name for <see cref="InspectionReadingDto.TextValue"/>.</summary>
    public static string InspectionReading_TextValue              => GetString(nameof(InspectionReading_TextValue));
    /// <summary>Display name for <see cref="InspectionReadingDto.Result"/>.</summary>
    public static string InspectionReading_Result                 => GetString(nameof(InspectionReading_Result));
    /// <summary>Display name for <see cref="InspectionReadingDto.Notes"/>.</summary>
    public static string InspectionReading_Notes                  => GetString(nameof(InspectionReading_Notes));
    /// <summary>Display name for <see cref="InspectionReadingDto.InspectionPointDescription"/>.</summary>
    public static string InspectionReading_PointDescription       => GetString(nameof(InspectionReading_PointDescription));
    /// <summary>Display name for <see cref="InspectionReadingDto.OperatorName"/>.</summary>
    public static string InspectionReading_OperatorName           => GetString(nameof(InspectionReading_OperatorName));
    /// <summary>Display name for <see cref="InspectionReadingDto.PhaseNumber"/>.</summary>
    public static string InspectionReading_PhaseNumber            => GetString(nameof(InspectionReading_PhaseNumber));

    // ── NonConformityDto ──────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="NonConformityDto.Code"/>.</summary>
    public static string NonConformity_Code                  => GetString(nameof(NonConformity_Code));
    /// <summary>Display name for <see cref="NonConformityDto.ProductionOrderPhaseId"/>.</summary>
    public static string NonConformity_ProductionOrderPhaseId => GetString(nameof(NonConformity_ProductionOrderPhaseId));
    /// <summary>Display name for <see cref="NonConformityDto.InspectionReadingId"/>.</summary>
    public static string NonConformity_InspectionReadingId   => GetString(nameof(NonConformity_InspectionReadingId));
    /// <summary>Display name for <see cref="NonConformityDto.Description"/>.</summary>
    public static string NonConformity_Description           => GetString(nameof(NonConformity_Description));
    /// <summary>Display name for <see cref="NonConformityDto.Type"/>.</summary>
    public static string NonConformity_Type                  => GetString(nameof(NonConformity_Type));
    /// <summary>Display name for <see cref="NonConformityDto.Severity"/>.</summary>
    public static string NonConformity_Severity              => GetString(nameof(NonConformity_Severity));
    /// <summary>Display name for <see cref="NonConformityDto.Status"/>.</summary>
    public static string NonConformity_Status                => GetString(nameof(NonConformity_Status));
    /// <summary>Display name for <see cref="NonConformityDto.CorrectiveAction"/>.</summary>
    public static string NonConformity_CorrectiveAction      => GetString(nameof(NonConformity_CorrectiveAction));
    /// <summary>Display name for <see cref="NonConformityDto.OpenedAt"/>.</summary>
    public static string NonConformity_OpenedAt              => GetString(nameof(NonConformity_OpenedAt));
    /// <summary>Display name for <see cref="NonConformityDto.ClosedAt"/>.</summary>
    public static string NonConformity_ClosedAt              => GetString(nameof(NonConformity_ClosedAt));
    /// <summary>Display name for <see cref="NonConformityDto.ClosedByOperatorId"/>.</summary>
    public static string NonConformity_ClosedByOperatorId    => GetString(nameof(NonConformity_ClosedByOperatorId));
    /// <summary>Display name for <see cref="NonConformityDto.Notes"/>.</summary>
    public static string NonConformity_Notes                 => GetString(nameof(NonConformity_Notes));
    /// <summary>Display name for <see cref="NonConformityDto.PhaseNumber"/>.</summary>
    public static string NonConformity_PhaseNumber           => GetString(nameof(NonConformity_PhaseNumber));
    /// <summary>Display name for <see cref="NonConformityDto.ClosedByOperatorName"/>.</summary>
    public static string NonConformity_ClosedByOperatorName  => GetString(nameof(NonConformity_ClosedByOperatorName));

    // ── StorageLocationDto ────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="StorageLocationDto.PlantId"/>.</summary>
    public static string StorageLocation_PlantId     => GetString(nameof(StorageLocation_PlantId));
    /// <summary>Display name for <see cref="StorageLocationDto.WarehouseId"/>.</summary>
    public static string StorageLocation_WarehouseId => GetString(nameof(StorageLocation_WarehouseId));
    /// <summary>Display name for <see cref="StorageLocationDto.Code"/>.</summary>
    public static string StorageLocation_Code        => GetString(nameof(StorageLocation_Code));
    /// <summary>Display name for <see cref="StorageLocationDto.Description"/>.</summary>
    public static string StorageLocation_Description  => GetString(nameof(StorageLocation_Description));
    /// <summary>Display name for <see cref="StorageLocationDto.Zone"/>.</summary>
    public static string StorageLocation_Zone         => GetString(nameof(StorageLocation_Zone));
    /// <summary>Display name for <see cref="StorageLocationDto.Slot"/>.</summary>
    public static string StorageLocation_Slot         => GetString(nameof(StorageLocation_Slot));
    /// <summary>Display name for <see cref="StorageLocationDto.Disabled"/>.</summary>
    public static string StorageLocation_Disabled     => GetString(nameof(StorageLocation_Disabled));

    // ── MaterialStockDto ──────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="MaterialStockDto.MaterialId"/>.</summary>
    public static string MaterialStock_MaterialId          => GetString(nameof(MaterialStock_MaterialId));
    /// <summary>Display name for <see cref="MaterialStockDto.StorageLocationId"/>.</summary>
    public static string MaterialStock_StorageLocationId   => GetString(nameof(MaterialStock_StorageLocationId));
    /// <summary>Display name for <see cref="MaterialStockDto.Quantity"/>.</summary>
    public static string MaterialStock_Quantity            => GetString(nameof(MaterialStock_Quantity));
    /// <summary>Display name for <see cref="MaterialStockDto.LastMovementDate"/>.</summary>
    public static string MaterialStock_LastMovementDate    => GetString(nameof(MaterialStock_LastMovementDate));
    /// <summary>Display name for <see cref="MaterialStockDto.PartNumber"/>.</summary>
    public static string MaterialStock_PartNumber          => GetString(nameof(MaterialStock_PartNumber));
    /// <summary>Display name for <see cref="MaterialStockDto.PartDescription"/>.</summary>
    public static string MaterialStock_PartDescription     => GetString(nameof(MaterialStock_PartDescription));
    /// <summary>Display name for <see cref="MaterialStockDto.UnitOfMeasure"/>.</summary>
    public static string MaterialStock_UnitOfMeasure       => GetString(nameof(MaterialStock_UnitOfMeasure));
    /// <summary>Display name for <see cref="MaterialStockDto.StorageLocationCode"/>.</summary>
    public static string MaterialStock_StorageLocationCode => GetString(nameof(MaterialStock_StorageLocationCode));
    /// <summary>Display name for <see cref="MaterialStockDto.Warehouse"/>.</summary>
    public static string MaterialStock_Warehouse           => GetString(nameof(MaterialStock_Warehouse));

    // ── StockMovementDto ──────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="StockMovementDto.MaterialId"/>.</summary>
    public static string StockMovement_MaterialId          => GetString(nameof(StockMovement_MaterialId));
    /// <summary>Display name for <see cref="StockMovementDto.StorageLocationId"/>.</summary>
    public static string StockMovement_StorageLocationId   => GetString(nameof(StockMovement_StorageLocationId));
    /// <summary>Display name for <see cref="StockMovementDto.MovementType"/>.</summary>
    public static string StockMovement_MovementType        => GetString(nameof(StockMovement_MovementType));
    /// <summary>Display name for <see cref="StockMovementDto.Quantity"/>.</summary>
    public static string StockMovement_Quantity            => GetString(nameof(StockMovement_Quantity));
    /// <summary>Display name for <see cref="StockMovementDto.MovementDate"/>.</summary>
    public static string StockMovement_MovementDate        => GetString(nameof(StockMovement_MovementDate));
    /// <summary>Display name for <see cref="StockMovementDto.ReferenceId"/>.</summary>
    public static string StockMovement_ReferenceId         => GetString(nameof(StockMovement_ReferenceId));
    /// <summary>Display name for <see cref="StockMovementDto.ReferenceType"/>.</summary>
    public static string StockMovement_ReferenceType       => GetString(nameof(StockMovement_ReferenceType));
    /// <summary>Display name for <see cref="StockMovementDto.OperatorId"/>.</summary>
    public static string StockMovement_OperatorId          => GetString(nameof(StockMovement_OperatorId));
    /// <summary>Display name for <see cref="StockMovementDto.Notes"/>.</summary>
    public static string StockMovement_Notes               => GetString(nameof(StockMovement_Notes));
    /// <summary>Display name for <see cref="StockMovementDto.PartNumber"/>.</summary>
    public static string StockMovement_PartNumber          => GetString(nameof(StockMovement_PartNumber));
    /// <summary>Display name for <see cref="StockMovementDto.PartDescription"/>.</summary>
    public static string StockMovement_PartDescription     => GetString(nameof(StockMovement_PartDescription));
    /// <summary>Display name for <see cref="StockMovementDto.StorageLocationCode"/>.</summary>
    public static string StockMovement_StorageLocationCode => GetString(nameof(StockMovement_StorageLocationCode));
    /// <summary>Display name for <see cref="StockMovementDto.OperatorName"/>.</summary>
    public static string StockMovement_OperatorName        => GetString(nameof(StockMovement_OperatorName));

    // ── PlantDto ──────────────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="PlantDto.Code"/>.</summary>
    public static string Plant_Code        => GetString(nameof(Plant_Code));
    /// <summary>Display name for <see cref="PlantDto.Description"/>.</summary>
    public static string Plant_Description => GetString(nameof(Plant_Description));

    // ── WorkCenterDto ─────────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="WorkCenterDto.PlantId"/>.</summary>
    public static string WorkCenter_PlantId     => GetString(nameof(WorkCenter_PlantId));
    /// <summary>Display name for <see cref="WorkCenterDto.Code"/>.</summary>
    public static string WorkCenter_Code        => GetString(nameof(WorkCenter_Code));
    /// <summary>Display name for <see cref="WorkCenterDto.Description"/>.</summary>
    public static string WorkCenter_Description => GetString(nameof(WorkCenter_Description));

    // ── MachineDto ────────────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="MachineDto.PlantId"/>.</summary>
    public static string Machine_PlantId     => GetString(nameof(Machine_PlantId));
    /// <summary>Display name for <see cref="MachineDto.WorkCenterId"/>.</summary>
    public static string Machine_WorkCenterId => GetString(nameof(Machine_WorkCenterId));
    /// <summary>Display name for <see cref="MachineDto.Code"/>.</summary>
    public static string Machine_Code        => GetString(nameof(Machine_Code));
    /// <summary>Display name for <see cref="MachineDto.Description"/>.</summary>
    public static string Machine_Description => GetString(nameof(Machine_Description));
    /// <summary>Display name for <see cref="MachineDto.Type"/>.</summary>
    public static string Machine_Type        => GetString(nameof(Machine_Type));
    /// <summary>Display name for <see cref="MachineDto.Status"/>.</summary>
    public static string Machine_Status      => GetString(nameof(Machine_Status));
    /// <summary>Display name for <see cref="MachineDto.Autoplacement"/>.</summary>
    public static string Machine_Autoplacement            => GetString(nameof(Machine_Autoplacement));
    /// <summary>Display name for <see cref="MachineDto.AllowConcurrentSessions"/>.</summary>
    public static string Machine_AllowConcurrentSessions  => GetString(nameof(Machine_AllowConcurrentSessions));
    /// <summary>Display name for <see cref="MachineDto.TimeAllocationMode"/>.</summary>
    public static string Machine_TimeAllocationMode       => GetString(nameof(Machine_TimeAllocationMode));

    // ── OperatorShiftDto ─────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="OperatorShiftDto.OperatorId"/>.</summary>
    public static string OperatorShift_OperatorId    => GetString(nameof(OperatorShift_OperatorId));
    /// <summary>Display name for <see cref="OperatorShiftDto.EventType"/>.</summary>
    public static string OperatorShift_EventType     => GetString(nameof(OperatorShift_EventType));
    /// <summary>Display name for <see cref="OperatorShiftDto.EventTime"/>.</summary>
    public static string OperatorShift_EventTime     => GetString(nameof(OperatorShift_EventTime));
    /// <summary>Display name for <see cref="OperatorShiftDto.Source"/>.</summary>
    public static string OperatorShift_Source        => GetString(nameof(OperatorShift_Source));
    /// <summary>Display name for <see cref="OperatorShiftDto.Notes"/>.</summary>
    public static string OperatorShift_Notes         => GetString(nameof(OperatorShift_Notes));
    /// <summary>Display name for <see cref="OperatorShiftDto.OperatorName"/>.</summary>
    public static string OperatorShift_OperatorName  => GetString(nameof(OperatorShift_OperatorName));

    // ── WorkSessionDto ───────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="WorkSessionDto.OperatorId"/>.</summary>
    public static string WorkSession_OperatorId              => GetString(nameof(WorkSession_OperatorId));
    /// <summary>Display name for <see cref="WorkSessionDto.ProductionOrderPhaseId"/>.</summary>
    public static string WorkSession_ProductionOrderPhaseId  => GetString(nameof(WorkSession_ProductionOrderPhaseId));
    /// <summary>Display name for <see cref="WorkSessionDto.MachineId"/>.</summary>
    public static string WorkSession_MachineId               => GetString(nameof(WorkSession_MachineId));
    /// <summary>Display name for <see cref="WorkSessionDto.SessionType"/>.</summary>
    public static string WorkSession_SessionType             => GetString(nameof(WorkSession_SessionType));
    /// <summary>Display name for <see cref="WorkSessionDto.Status"/>.</summary>
    public static string WorkSession_Status                  => GetString(nameof(WorkSession_Status));
    /// <summary>Display name for <see cref="WorkSessionDto.StartTime"/>.</summary>
    public static string WorkSession_StartTime               => GetString(nameof(WorkSession_StartTime));
    /// <summary>Display name for <see cref="WorkSessionDto.EndTime"/>.</summary>
    public static string WorkSession_EndTime                 => GetString(nameof(WorkSession_EndTime));
    /// <summary>Display name for <see cref="WorkSessionDto.AllocatedMinutes"/>.</summary>
    public static string WorkSession_AllocatedMinutes        => GetString(nameof(WorkSession_AllocatedMinutes));
    /// <summary>Display name for <see cref="WorkSessionDto.Source"/>.</summary>
    public static string WorkSession_Source                  => GetString(nameof(WorkSession_Source));
    /// <summary>Display name for <see cref="WorkSessionDto.Notes"/>.</summary>
    public static string WorkSession_Notes                   => GetString(nameof(WorkSession_Notes));
    /// <summary>Display name for <see cref="WorkSessionDto.PhaseExternalId"/>.</summary>
    public static string WorkSession_PhaseExternalId         => GetString(nameof(WorkSession_PhaseExternalId));
    /// <summary>Display name for <see cref="WorkSessionDto.ExternalCounterId"/>.</summary>
    public static string WorkSession_ExternalCounterId       => GetString(nameof(WorkSession_ExternalCounterId));
    /// <summary>Display name for <see cref="WorkSessionDto.ErpExportedAt"/>.</summary>
    public static string WorkSession_ErpExportedAt           => GetString(nameof(WorkSession_ErpExportedAt));
    /// <summary>Display name for <see cref="WorkSessionDto.IsReversal"/>.</summary>
    public static string WorkSession_IsReversal              => GetString(nameof(WorkSession_IsReversal));
    /// <summary>Display name for <see cref="WorkSessionDto.ReversalOfId"/>.</summary>
    public static string WorkSession_ReversalOfId            => GetString(nameof(WorkSession_ReversalOfId));
    /// <summary>Display name for <see cref="WorkSessionDto.ReversedById"/>.</summary>
    public static string WorkSession_ReversedById            => GetString(nameof(WorkSession_ReversedById));
    /// <summary>Display name for <see cref="WorkSessionDto.OperatorName"/>.</summary>
    public static string WorkSession_OperatorName            => GetString(nameof(WorkSession_OperatorName));
    /// <summary>Display name for <see cref="WorkSessionDto.PhaseNumber"/>.</summary>
    public static string WorkSession_PhaseNumber             => GetString(nameof(WorkSession_PhaseNumber));
    /// <summary>Display name for <see cref="WorkSessionDto.MachineCode"/>.</summary>
    public static string WorkSession_MachineCode             => GetString(nameof(WorkSession_MachineCode));

    // ── MachinePhasePlacementDto ─────────────────────────────────────────────
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.MachineId"/>.</summary>
    public static string MachinePhasePlacement_MachineId               => GetString(nameof(MachinePhasePlacement_MachineId));
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.ProductionOrderPhaseId"/>.</summary>
    public static string MachinePhasePlacement_ProductionOrderPhaseId  => GetString(nameof(MachinePhasePlacement_ProductionOrderPhaseId));
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.PlacedByOperatorId"/>.</summary>
    public static string MachinePhasePlacement_PlacedByOperatorId      => GetString(nameof(MachinePhasePlacement_PlacedByOperatorId));
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.PlacedAt"/>.</summary>
    public static string MachinePhasePlacement_PlacedAt                => GetString(nameof(MachinePhasePlacement_PlacedAt));
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.UnplacedAt"/>.</summary>
    public static string MachinePhasePlacement_UnplacedAt              => GetString(nameof(MachinePhasePlacement_UnplacedAt));
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.Status"/>.</summary>
    public static string MachinePhasePlacement_Status                  => GetString(nameof(MachinePhasePlacement_Status));
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.Source"/>.</summary>
    public static string MachinePhasePlacement_Source                  => GetString(nameof(MachinePhasePlacement_Source));
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.Notes"/>.</summary>
    public static string MachinePhasePlacement_Notes                   => GetString(nameof(MachinePhasePlacement_Notes));
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.MachineCode"/>.</summary>
    public static string MachinePhasePlacement_MachineCode             => GetString(nameof(MachinePhasePlacement_MachineCode));
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.PhaseNumber"/>.</summary>
    public static string MachinePhasePlacement_PhaseNumber             => GetString(nameof(MachinePhasePlacement_PhaseNumber));
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.PhaseConfirmNumber"/>.</summary>
    public static string MachinePhasePlacement_PhaseConfirmNumber      => GetString(nameof(MachinePhasePlacement_PhaseConfirmNumber));
    /// <summary>Display name for <see cref="MachinePhasePlacementDto.PlacedByOperatorName"/>.</summary>
    public static string MachinePhasePlacement_PlacedByOperatorName    => GetString(nameof(MachinePhasePlacement_PlacedByOperatorName));

    // ── WarehouseDto ─────────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="WarehouseDto.PlantId"/>.</summary>
    public static string Warehouse_PlantId      => GetString(nameof(Warehouse_PlantId));
    /// <summary>Display name for <see cref="WarehouseDto.Code"/>.</summary>
    public static string Warehouse_Code         => GetString(nameof(Warehouse_Code));
    /// <summary>Display name for <see cref="WarehouseDto.Description"/>.</summary>
    public static string Warehouse_Description  => GetString(nameof(Warehouse_Description));
    /// <summary>Display name for <see cref="WarehouseDto.Disabled"/>.</summary>
    public static string Warehouse_Disabled     => GetString(nameof(Warehouse_Disabled));

    // ── MachineStateDto ──────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="MachineStateDto.MachineId"/>.</summary>
    public static string MachineState_MachineId    => GetString(nameof(MachineState_MachineId));
    /// <summary>Display name for <see cref="MachineStateDto.Status"/>.</summary>
    public static string MachineState_Status       => GetString(nameof(MachineState_Status));
    /// <summary>Display name for <see cref="MachineStateDto.EventTime"/>.</summary>
    public static string MachineState_EventTime    => GetString(nameof(MachineState_EventTime));
    /// <summary>Display name for <see cref="MachineStateDto.Source"/>.</summary>
    public static string MachineState_Source       => GetString(nameof(MachineState_Source));
    /// <summary>Display name for <see cref="MachineStateDto.OperatorId"/>.</summary>
    public static string MachineState_OperatorId   => GetString(nameof(MachineState_OperatorId));
    /// <summary>Display name for <see cref="MachineStateDto.Notes"/>.</summary>
    public static string MachineState_Notes        => GetString(nameof(MachineState_Notes));
    /// <summary>Display name for <see cref="MachineStateDto.MachineCode"/>.</summary>
    public static string MachineState_MachineCode  => GetString(nameof(MachineState_MachineCode));
    /// <summary>Display name for <see cref="MachineStateDto.OperatorName"/>.</summary>
    public static string MachineState_OperatorName => GetString(nameof(MachineState_OperatorName));

    // ── OperatorDto ───────────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="OperatorDto.EmployeeNumber"/>.</summary>
    public static string Operator_EmployeeNumber => GetString(nameof(Operator_EmployeeNumber));
    /// <summary>Display name for <see cref="OperatorDto.Name"/>.</summary>
    public static string Operator_Name           => GetString(nameof(Operator_Name));
    /// <summary>Display name for <see cref="OperatorDto.Badge"/>.</summary>
    public static string Operator_Badge          => GetString(nameof(Operator_Badge));

    // ── MaterialDto ───────────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="MaterialDto.PartNumber"/>.</summary>
    public static string Material_PartNumber     => GetString(nameof(Material_PartNumber));
    /// <summary>Display name for <see cref="MaterialDto.PartDescription"/>.</summary>
    public static string Material_PartDescription => GetString(nameof(Material_PartDescription));
    /// <summary>Display name for <see cref="MaterialDto.PartType"/>.</summary>
    public static string Material_PartType       => GetString(nameof(Material_PartType));
    /// <summary>Display name for <see cref="MaterialDto.PartGroup"/>.</summary>
    public static string Material_PartGroup      => GetString(nameof(Material_PartGroup));
    /// <summary>Display name for <see cref="MaterialDto.UnitOfMeasure"/>.</summary>
    public static string Material_UnitOfMeasure  => GetString(nameof(Material_UnitOfMeasure));
    /// <summary>Display name for <see cref="MaterialDto.IsConsumable"/>.</summary>
    public static string Material_IsConsumable   => GetString(nameof(Material_IsConsumable));
    /// <summary>Display name for <see cref="MaterialDto.IsPhantom"/>.</summary>
    public static string Material_IsPhantom      => GetString(nameof(Material_IsPhantom));
    /// <summary>Display name for <see cref="MaterialDto.AllowOverproduction"/>.</summary>
    public static string Material_AllowOverproduction      => GetString(nameof(Material_AllowOverproduction));
    /// <summary>Display name for <see cref="MaterialDto.DefaultWarehouseId"/>.</summary>
    public static string Material_DefaultWarehouseId       => GetString(nameof(Material_DefaultWarehouseId));
    /// <summary>Display name for <see cref="MaterialDto.DefaultStorageLocationId"/>.</summary>
    public static string Material_DefaultStorageLocationId => GetString(nameof(Material_DefaultStorageLocationId));

    // ── ProductionOrderDto ────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="ProductionOrderDto.PlantId"/>.</summary>
    public static string ProductionOrder_PlantId            => GetString(nameof(ProductionOrder_PlantId));
    /// <summary>Display name for <see cref="ProductionOrderDto.MaterialId"/>.</summary>
    public static string ProductionOrder_MaterialId         => GetString(nameof(ProductionOrder_MaterialId));
    /// <summary>Display name for <see cref="ProductionOrderDto.OrderNumber"/>.</summary>
    public static string ProductionOrder_OrderNumber        => GetString(nameof(ProductionOrder_OrderNumber));
    /// <summary>Display name for <see cref="ProductionOrderDto.OrderType"/>.</summary>
    public static string ProductionOrder_OrderType          => GetString(nameof(ProductionOrder_OrderType));
    /// <summary>Display name for <see cref="ProductionOrderDto.PlannedQuantity"/>.</summary>
    public static string ProductionOrder_PlannedQuantity    => GetString(nameof(ProductionOrder_PlannedQuantity));
    /// <summary>Display name for <see cref="ProductionOrderDto.ConfirmedQuantity"/>.</summary>
    public static string ProductionOrder_ConfirmedQuantity  => GetString(nameof(ProductionOrder_ConfirmedQuantity));
    /// <summary>Display name for <see cref="ProductionOrderDto.ScrapQuantity"/>.</summary>
    public static string ProductionOrder_ScrapQuantity      => GetString(nameof(ProductionOrder_ScrapQuantity));
    /// <summary>Display name for <see cref="ProductionOrderDto.PlantName"/>.</summary>
    public static string ProductionOrder_PlantName          => GetString(nameof(ProductionOrder_PlantName));
    /// <summary>Display name for <see cref="ProductionOrderDto.PartNumber"/>.</summary>
    public static string ProductionOrder_PartNumber         => GetString(nameof(ProductionOrder_PartNumber));
    /// <summary>Display name for <see cref="ProductionOrderDto.PartDescription"/>.</summary>
    public static string ProductionOrder_PartDescription    => GetString(nameof(ProductionOrder_PartDescription));

    // ── ProductionOrderPhaseDto ───────────────────────────────────────────────
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.ProductionOrderId"/>.</summary>
    public static string ProductionOrderPhase_ProductionOrderId  => GetString(nameof(ProductionOrderPhase_ProductionOrderId));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.PhaseNumber"/>.</summary>
    public static string ProductionOrderPhase_PhaseNumber        => GetString(nameof(ProductionOrderPhase_PhaseNumber));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.WorkCenterId"/>.</summary>
    public static string ProductionOrderPhase_WorkCenterId       => GetString(nameof(ProductionOrderPhase_WorkCenterId));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.WorkCode"/>.</summary>
    public static string ProductionOrderPhase_WorkCode           => GetString(nameof(ProductionOrderPhase_WorkCode));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.Description"/>.</summary>
    public static string ProductionOrderPhase_Description        => GetString(nameof(ProductionOrderPhase_Description));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.ConfirmNumber"/>.</summary>
    public static string ProductionOrderPhase_ConfirmNumber      => GetString(nameof(ProductionOrderPhase_ConfirmNumber));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.StartDate"/>.</summary>
    public static string ProductionOrderPhase_StartDate          => GetString(nameof(ProductionOrderPhase_StartDate));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.EndDate"/>.</summary>
    public static string ProductionOrderPhase_EndDate            => GetString(nameof(ProductionOrderPhase_EndDate));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.PlannedQuantity"/>.</summary>
    public static string ProductionOrderPhase_PlannedQuantity    => GetString(nameof(ProductionOrderPhase_PlannedQuantity));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.CounterQuantity"/>.</summary>
    public static string ProductionOrderPhase_CounterQuantity    => GetString(nameof(ProductionOrderPhase_CounterQuantity));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.ConfirmedQuantity"/>.</summary>
    public static string ProductionOrderPhase_ConfirmedQuantity  => GetString(nameof(ProductionOrderPhase_ConfirmedQuantity));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.ScrapQuantity"/>.</summary>
    public static string ProductionOrderPhase_ScrapQuantity      => GetString(nameof(ProductionOrderPhase_ScrapQuantity));
    /// <summary>Display name for <see cref="ProductionOrderPhaseDto.Status"/>.</summary>
    public static string ProductionOrderPhase_Status             => GetString(nameof(ProductionOrderPhase_Status));

    // ── ProductionJobDto ──────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="ProductionJobDto.ProductionOrderPhaseId"/>.</summary>
    public static string ProductionJob_ProductionOrderPhaseId => GetString(nameof(ProductionJob_ProductionOrderPhaseId));
    /// <summary>Display name for <see cref="ProductionJobDto.JobId"/>.</summary>
    public static string ProductionJob_JobId                  => GetString(nameof(ProductionJob_JobId));
    /// <summary>Display name for <see cref="ProductionJobDto.PlannedQuantity"/>.</summary>
    public static string ProductionJob_PlannedQuantity        => GetString(nameof(ProductionJob_PlannedQuantity));
    /// <summary>Display name for <see cref="ProductionJobDto.PlannedSetupTime"/>.</summary>
    public static string ProductionJob_PlannedSetupTime       => GetString(nameof(ProductionJob_PlannedSetupTime));
    /// <summary>Display name for <see cref="ProductionJobDto.PlannedRunTime"/>.</summary>
    public static string ProductionJob_PlannedRunTime         => GetString(nameof(ProductionJob_PlannedRunTime));
    /// <summary>Display name for <see cref="ProductionJobDto.PhaseNumber"/>.</summary>
    public static string ProductionJob_PhaseNumber            => GetString(nameof(ProductionJob_PhaseNumber));

    // ── ClientDeviceDto ───────────────────────────────────────────────────────
    /// <summary>Display name for <see cref="ClientDeviceDto.PlantId"/>.</summary>
    public static string ClientDevice_PlantId     => GetString(nameof(ClientDevice_PlantId));
    /// <summary>Display name for <see cref="ClientDeviceDto.Name"/>.</summary>
    public static string ClientDevice_Name        => GetString(nameof(ClientDevice_Name));
    /// <summary>Display name for <see cref="ClientDeviceDto.Description"/>.</summary>
    public static string ClientDevice_Description => GetString(nameof(ClientDevice_Description));
    /// <summary>Display name for <see cref="ClientDeviceDto.Enabled"/>.</summary>
    public static string ClientDevice_Enabled     => GetString(nameof(ClientDevice_Enabled));

    // ── PhasePickingListDto ───────────────────────────────────────────────────
    /// <summary>Display name for <see cref="PhasePickingListDto.ProductionOrderPhaseId"/>.</summary>
    public static string PhasePickingList_ProductionOrderPhaseId => GetString(nameof(PhasePickingList_ProductionOrderPhaseId));
    /// <summary>Display name for <see cref="PhasePickingListDto.MaterialId"/>.</summary>
    public static string PhasePickingList_MaterialId             => GetString(nameof(PhasePickingList_MaterialId));
    /// <summary>Display name for <see cref="PhasePickingListDto.StorageLocationId"/>.</summary>
    public static string PhasePickingList_StorageLocationId      => GetString(nameof(PhasePickingList_StorageLocationId));
    /// <summary>Display name for <see cref="PhasePickingListDto.RequiredQuantity"/>.</summary>
    public static string PhasePickingList_RequiredQuantity       => GetString(nameof(PhasePickingList_RequiredQuantity));
    /// <summary>Display name for <see cref="PhasePickingListDto.PickedQuantity"/>.</summary>
    public static string PhasePickingList_PickedQuantity         => GetString(nameof(PhasePickingList_PickedQuantity));
    /// <summary>Display name for <see cref="PhasePickingListDto.IsAutomatic"/>.</summary>
    public static string PhasePickingList_IsAutomatic            => GetString(nameof(PhasePickingList_IsAutomatic));
    /// <summary>Display name for <see cref="PhasePickingListDto.IsConsumable"/>.</summary>
    public static string PhasePickingList_IsConsumable           => GetString(nameof(PhasePickingList_IsConsumable));
    /// <summary>Display name for <see cref="PhasePickingListDto.IsPhantom"/>.</summary>
    public static string PhasePickingList_IsPhantom              => GetString(nameof(PhasePickingList_IsPhantom));
    /// <summary>Display name for <see cref="PhasePickingListDto.Status"/>.</summary>
    public static string PhasePickingList_Status                 => GetString(nameof(PhasePickingList_Status));
    /// <summary>Display name for <see cref="PhasePickingListDto.Notes"/>.</summary>
    public static string PhasePickingList_Notes                  => GetString(nameof(PhasePickingList_Notes));
    /// <summary>Display name for <see cref="PhasePickingListDto.PhaseNumber"/>.</summary>
    public static string PhasePickingList_PhaseNumber            => GetString(nameof(PhasePickingList_PhaseNumber));
    /// <summary>Display name for <see cref="PhasePickingListDto.PartNumber"/>.</summary>
    public static string PhasePickingList_PartNumber             => GetString(nameof(PhasePickingList_PartNumber));
    /// <summary>Display name for <see cref="PhasePickingListDto.PartDescription"/>.</summary>
    public static string PhasePickingList_PartDescription        => GetString(nameof(PhasePickingList_PartDescription));
    /// <summary>Display name for <see cref="PhasePickingListDto.UnitOfMeasure"/>.</summary>
    public static string PhasePickingList_UnitOfMeasure          => GetString(nameof(PhasePickingList_UnitOfMeasure));
    /// <summary>Display name for <see cref="PhasePickingListDto.StorageLocationCode"/>.</summary>
    public static string PhasePickingList_StorageLocationCode    => GetString(nameof(PhasePickingList_StorageLocationCode));

    // ── PhasePickingItemDto ───────────────────────────────────────────────────
    /// <summary>Display name for <see cref="PhasePickingItemDto.PhasePickingListId"/>.</summary>
    public static string PhasePickingItem_PhasePickingListId    => GetString(nameof(PhasePickingItem_PhasePickingListId));
    /// <summary>Display name for <see cref="PhasePickingItemDto.StockMovementId"/>.</summary>
    public static string PhasePickingItem_StockMovementId       => GetString(nameof(PhasePickingItem_StockMovementId));
    /// <summary>Display name for <see cref="PhasePickingItemDto.PickedQuantity"/>.</summary>
    public static string PhasePickingItem_PickedQuantity        => GetString(nameof(PhasePickingItem_PickedQuantity));
    /// <summary>Display name for <see cref="PhasePickingItemDto.PickedAt"/>.</summary>
    public static string PhasePickingItem_PickedAt              => GetString(nameof(PhasePickingItem_PickedAt));
    /// <summary>Display name for <see cref="PhasePickingItemDto.OperatorId"/>.</summary>
    public static string PhasePickingItem_OperatorId            => GetString(nameof(PhasePickingItem_OperatorId));
    /// <summary>Display name for <see cref="PhasePickingItemDto.IsAutomatic"/>.</summary>
    public static string PhasePickingItem_IsAutomatic           => GetString(nameof(PhasePickingItem_IsAutomatic));
    /// <summary>Display name for <see cref="PhasePickingItemDto.Notes"/>.</summary>
    public static string PhasePickingItem_Notes                 => GetString(nameof(PhasePickingItem_Notes));
    /// <summary>Display name for <see cref="PhasePickingItemDto.OperatorName"/>.</summary>
    public static string PhasePickingItem_OperatorName          => GetString(nameof(PhasePickingItem_OperatorName));
    /// <summary>Display name for <see cref="PhasePickingItemDto.PartNumber"/>.</summary>
    public static string PhasePickingItem_PartNumber            => GetString(nameof(PhasePickingItem_PartNumber));
    /// <summary>Display name for <see cref="PhasePickingItemDto.StorageLocationCode"/>.</summary>
    public static string PhasePickingItem_StorageLocationCode   => GetString(nameof(PhasePickingItem_StorageLocationCode));
}
