using OpenMES.Data.Common;
using OpenMES.Data.Dtos.Resources;
using System.ComponentModel.DataAnnotations;

namespace OpenMES.Data.Dtos;

public class PhasePickingItemDto : IKey<int>
{
	/// <summary>Unique identifier of the picking item.</summary>
	public int Id { get; set; }

	/// <summary>FK to the picking list line this item fulfills.</summary>
	[Display(Name = nameof(DtoResources.PhasePickingItem_PhasePickingListId), ResourceType = typeof(DtoResources))]
	public int PhasePickingListId { get; set; }

	/// <summary>FK to the stock movement generated by this picking event.</summary>
	[Display(Name = nameof(DtoResources.PhasePickingItem_StockMovementId), ResourceType = typeof(DtoResources))]
	public int StockMovementId { get; set; }

	/// <summary>Quantity picked in this event.</summary>
	[Display(Name = nameof(DtoResources.PhasePickingItem_PickedQuantity), ResourceType = typeof(DtoResources))]
	public decimal PickedQuantity { get; set; }

	/// <summary>Date and time the picking was performed.</summary>
	[Display(Name = nameof(DtoResources.PhasePickingItem_PickedAt), ResourceType = typeof(DtoResources))]
	public DateTimeOffset PickedAt { get; set; }

	/// <summary>FK to the operator who performed or confirmed the picking.</summary>
	[Display(Name = nameof(DtoResources.PhasePickingItem_OperatorId), ResourceType = typeof(DtoResources))]
	public int OperatorId { get; set; }

	/// <summary>True when this item was generated automatically by a ProductionDeclaration.</summary>
	[Display(Name = nameof(DtoResources.PhasePickingItem_IsAutomatic), ResourceType = typeof(DtoResources))]
	public bool IsAutomatic { get; set; }

	/// <summary>Free-text notes about this picking event.</summary>
	[StringLength(500)]
	[Display(Name = nameof(DtoResources.PhasePickingItem_Notes), ResourceType = typeof(DtoResources))]
	public string? Notes { get; set; }

	/// <summary>Timestamp of record creation (UTC).</summary>
	public DateTimeOffset CreatedAt { get; set; }

	/// <summary>Timestamp of last record update (UTC).</summary>
	public DateTimeOffset UpdatedAt { get; set; }

	// Denormalized for display
	/// <summary>Full name of the operator who performed the picking (denormalized for display).</summary>
	[Display(Name = nameof(DtoResources.PhasePickingItem_OperatorName), ResourceType = typeof(DtoResources))]
	public string? OperatorName { get; set; }

	/// <summary>Part number of the picked material (denormalized for display).</summary>
	[Display(Name = nameof(DtoResources.PhasePickingItem_PartNumber), ResourceType = typeof(DtoResources))]
	public string? PartNumber { get; set; }

	/// <summary>Code of the source storage location (denormalized for display).</summary>
	[Display(Name = nameof(DtoResources.PhasePickingItem_StorageLocationCode), ResourceType = typeof(DtoResources))]
	public string? StorageLocationCode { get; set; }
}
