// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenMES.Data.Contexts;

#nullable disable

namespace OpenMES.Data.Pgsql.DataMigrations
{
    [DbContext(typeof(OpenMESDbContext))]
    partial class OpenMESDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenMES.Data.Entities.ClientDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PlantId");

                    b.ToTable("ClientDevice");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ClientMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientDeviceId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientDeviceId");

                    b.HasIndex("MachineId");

                    b.ToTable("ClientMachines");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.InspectionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Version")
                        .IsUnique();

                    b.ToTable("InspectionPlan");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.InspectionPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("InspectionPlanId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LowerTolerance")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<byte>("MeasureType")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("NominalValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("UpperTolerance")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("InspectionPlanId");

                    b.ToTable("InspectionPoint");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.InspectionReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InspectionPointId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionOrderPhaseId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReadingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Result")
                        .HasColumnType("smallint");

                    b.Property<string>("TextValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InspectionPointId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductionOrderPhaseId");

                    b.ToTable("InspectionReading");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowConcurrentSessions")
                        .HasColumnType("boolean");

                    b.Property<bool>("Autoplacement")
                        .HasColumnType("boolean");

                    b.Property<int?>("ClientDeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<byte>("TimeAllocationMode")
                        .HasColumnType("smallint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkCenterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientDeviceId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("WorkCenterId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.MachinePhasePlacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlacedByOperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionOrderPhaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("UnplacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlacedByOperatorId");

                    b.HasIndex("ProductionOrderPhaseId");

                    b.HasIndex("MachineId", "ProductionOrderPhaseId", "UnplacedAt");

                    b.ToTable("MachinePhasePlacement");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.MachineState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("OperatorId");

                    b.ToTable("MachineState");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.MachineStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<int>("MachineStopReasonId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ProductionOrderPhaseId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("MachineStopReasonId");

                    b.HasIndex("ProductionOrderPhaseId");

                    b.ToTable("MachineStop");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.MachineStopReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("Category")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MachineStopReason");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowOverproduction")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultStorageLocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultWarehouseId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhantom")
                        .HasColumnType("boolean");

                    b.Property<string>("PartDescription")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PartGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DefaultStorageLocationId");

                    b.HasIndex("DefaultWarehouseId");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("Material");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.MaterialStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("LastMovementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<int>("StorageLocationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageLocationId");

                    b.HasIndex("MaterialId", "StorageLocationId")
                        .IsUnique();

                    b.ToTable("MaterialStock");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.NonConformity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ClosedByOperatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CorrectiveAction")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("InspectionReadingId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductionOrderPhaseId")
                        .HasColumnType("integer");

                    b.Property<byte>("Severity")
                        .HasColumnType("smallint");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByOperatorId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("InspectionReadingId")
                        .IsUnique();

                    b.HasIndex("ProductionOrderPhaseId");

                    b.ToTable("NonConformity");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Operator");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.OperatorShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("EventType")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("OperatorShift");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.PhasePickingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("PhasePickingListId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PickedQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<int>("StockMovementId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PhasePickingListId");

                    b.HasIndex("StockMovementId");

                    b.ToTable("PhasePickingItem");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.PhasePickingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhantom")
                        .HasColumnType("boolean");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PickedQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<int>("ProductionOrderPhaseId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RequiredQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<int?>("StorageLocationId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionOrderPhaseId");

                    b.HasIndex("StorageLocationId");

                    b.ToTable("PhasePickingList");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Plant");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ProductionDeclaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConfirmedQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DeclarationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ErpExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalCounterId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsReversal")
                        .HasColumnType("boolean");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<string>("PhaseExternalId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ProductionOrderPhaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReversalOfId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReversedById")
                        .HasColumnType("integer");

                    b.Property<decimal>("ScrapQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductionOrderPhaseId");

                    b.ToTable("ProductionDeclaration");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ProductionJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("PlannedQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("PlannedRunTime")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("PlannedSetupTime")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<int>("ProductionOrderPhaseId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderPhaseId");

                    b.ToTable("ProductionJob");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConfirmedQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("PlannedQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ScrapQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PlantId");

                    b.ToTable("ProductionOrder");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ProductionOrderPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConfirmedQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("CounterQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PhaseNumber")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<decimal>("PlannedQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ScrapQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkCenterId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ExternalId");

                    b.HasIndex("WorkCenterId");

                    b.HasIndex("ProductionOrderId", "PhaseNumber")
                        .IsUnique();

                    b.ToTable("ProductionOrderPhase");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MovementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("MovementType")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StorageLocationId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("StorageLocationId");

                    b.ToTable("StockMovement");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.StorageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Slot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.Property<string>("Zone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("StorageLocation");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.WorkCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PlantId");

                    b.ToTable("WorkCenter");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.WorkSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedMinutes")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ErpExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalCounterId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsReversal")
                        .HasColumnType("boolean");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<string>("PhaseExternalId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ProductionOrderPhaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReversalOfId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReversedById")
                        .HasColumnType("integer");

                    b.Property<byte>("SessionType")
                        .HasColumnType("smallint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductionOrderPhaseId");

                    b.ToTable("WorkSession");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ClientDevice", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ClientMachine", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.ClientDevice", "ClientDevice")
                        .WithMany()
                        .HasForeignKey("ClientDeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClientDevice");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.InspectionPoint", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.InspectionPlan", "InspectionPlan")
                        .WithMany("InspectionPoints")
                        .HasForeignKey("InspectionPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InspectionPlan");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.InspectionReading", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.InspectionPoint", "InspectionPoint")
                        .WithMany("InspectionReadings")
                        .HasForeignKey("InspectionPointId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.ProductionOrderPhase", "ProductionOrderPhase")
                        .WithMany("InspectionReadings")
                        .HasForeignKey("ProductionOrderPhaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InspectionPoint");

                    b.Navigation("Operator");

                    b.Navigation("ProductionOrderPhase");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Machine", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.ClientDevice", null)
                        .WithMany("Machines")
                        .HasForeignKey("ClientDeviceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OpenMES.Data.Entities.WorkCenter", "WorkCenter")
                        .WithMany("Machines")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.MachinePhasePlacement", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Machine", "Machine")
                        .WithMany("PhasePlacements")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.Operator", "PlacedByOperator")
                        .WithMany()
                        .HasForeignKey("PlacedByOperatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.ProductionOrderPhase", "ProductionOrderPhase")
                        .WithMany("MachinePhasePlacements")
                        .HasForeignKey("ProductionOrderPhaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("PlacedByOperator");

                    b.Navigation("ProductionOrderPhase");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.MachineState", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Machine", "Machine")
                        .WithMany("MachineStates")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Machine");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.MachineStop", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.MachineStopReason", "MachineStopReason")
                        .WithMany("MachineStops")
                        .HasForeignKey("MachineStopReasonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.ProductionOrderPhase", "ProductionOrderPhase")
                        .WithMany()
                        .HasForeignKey("ProductionOrderPhaseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Machine");

                    b.Navigation("MachineStopReason");

                    b.Navigation("ProductionOrderPhase");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Material", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.StorageLocation", "DefaultStorageLocation")
                        .WithMany()
                        .HasForeignKey("DefaultStorageLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OpenMES.Data.Entities.Warehouse", "DefaultWarehouse")
                        .WithMany("Materials")
                        .HasForeignKey("DefaultWarehouseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DefaultStorageLocation");

                    b.Navigation("DefaultWarehouse");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.MaterialStock", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Material", "Material")
                        .WithMany("MaterialStocks")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.StorageLocation", "StorageLocation")
                        .WithMany("MaterialStocks")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.NonConformity", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Operator", "ClosedByOperator")
                        .WithMany()
                        .HasForeignKey("ClosedByOperatorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OpenMES.Data.Entities.InspectionReading", "InspectionReading")
                        .WithOne("NonConformity")
                        .HasForeignKey("OpenMES.Data.Entities.NonConformity", "InspectionReadingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OpenMES.Data.Entities.ProductionOrderPhase", "ProductionOrderPhase")
                        .WithMany("NonConformities")
                        .HasForeignKey("ProductionOrderPhaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClosedByOperator");

                    b.Navigation("InspectionReading");

                    b.Navigation("ProductionOrderPhase");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Operator", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Plant", "Plant")
                        .WithMany("Operators")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.OperatorShift", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.PhasePickingItem", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.PhasePickingList", "PhasePickingList")
                        .WithMany("PickingItems")
                        .HasForeignKey("PhasePickingListId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.StockMovement", "StockMovement")
                        .WithMany()
                        .HasForeignKey("StockMovementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("PhasePickingList");

                    b.Navigation("StockMovement");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.PhasePickingList", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.ProductionOrderPhase", "ProductionOrderPhase")
                        .WithMany("PickingLines")
                        .HasForeignKey("ProductionOrderPhaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Material");

                    b.Navigation("ProductionOrderPhase");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ProductionDeclaration", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.ProductionOrderPhase", "ProductionOrderPhase")
                        .WithMany("ProductionDeclarations")
                        .HasForeignKey("ProductionOrderPhaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Operator");

                    b.Navigation("ProductionOrderPhase");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ProductionJob", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.ProductionOrderPhase", "ProductionOrderPhase")
                        .WithMany("ProductionJobs")
                        .HasForeignKey("ProductionOrderPhaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductionOrderPhase");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ProductionOrder", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Material", "Material")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.Plant", "Plant")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ProductionOrderPhase", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("ProductionOrderPhases")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductionOrder");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.StockMovement", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Material", "Material")
                        .WithMany("StockMovements")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.StorageLocation", "StorageLocation")
                        .WithMany("StockMovements")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Operator");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.StorageLocation", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Warehouse", "Warehouse")
                        .WithMany("StorageLocations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Warehouse", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Plant", "Plant")
                        .WithMany("Warehouses")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.WorkCenter", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Plant", "Plant")
                        .WithMany("WorkCenters")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.WorkSession", b =>
                {
                    b.HasOne("OpenMES.Data.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OpenMES.Data.Entities.ProductionOrderPhase", "ProductionOrderPhase")
                        .WithMany("WorkSessions")
                        .HasForeignKey("ProductionOrderPhaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Operator");

                    b.Navigation("ProductionOrderPhase");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ClientDevice", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.InspectionPlan", b =>
                {
                    b.Navigation("InspectionPoints");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.InspectionPoint", b =>
                {
                    b.Navigation("InspectionReadings");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.InspectionReading", b =>
                {
                    b.Navigation("NonConformity");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Machine", b =>
                {
                    b.Navigation("MachineStates");

                    b.Navigation("PhasePlacements");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.MachineStopReason", b =>
                {
                    b.Navigation("MachineStops");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Material", b =>
                {
                    b.Navigation("MaterialStocks");

                    b.Navigation("ProductionOrders");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.PhasePickingList", b =>
                {
                    b.Navigation("PickingItems");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Plant", b =>
                {
                    b.Navigation("Operators");

                    b.Navigation("ProductionOrders");

                    b.Navigation("Warehouses");

                    b.Navigation("WorkCenters");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ProductionOrder", b =>
                {
                    b.Navigation("ProductionOrderPhases");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.ProductionOrderPhase", b =>
                {
                    b.Navigation("InspectionReadings");

                    b.Navigation("MachinePhasePlacements");

                    b.Navigation("NonConformities");

                    b.Navigation("PickingLines");

                    b.Navigation("ProductionDeclarations");

                    b.Navigation("ProductionJobs");

                    b.Navigation("WorkSessions");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.StorageLocation", b =>
                {
                    b.Navigation("MaterialStocks");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.Warehouse", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("StorageLocations");
                });

            modelBuilder.Entity("OpenMES.Data.Entities.WorkCenter", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
